version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3010:3010'

  next:
    build: ./next
    ports:
      - '3000:3000'

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443' # Add HTTPS port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx configurations
      - ./certbot/conf:/etc/letsencrypt # Certbot certificates
      - ./certbot/www:/var/www/certbot # Webroot for ACME challenge

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email fazlomr9@gmail.com -d localhost --agree-tos


  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
