services:
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/usr/src/app/uploads # Adjusted mapping

  next:
    build: ./next

  caddy:
    image: caddy
    ports:
      - '80:80'
      - '443:443'
      - '3010:3010'
    volumes:
      - ./caddy/data/:/data/
      - ./caddy/config/:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile

  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
