version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3010:3010'
    volumes:
      - ./backend/uploads:/usr/src/app/uploads  # Adjusted mapping

  next:
    build: ./next
    ports:
      - '3000:3000'
  
  caddy:
    image: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/data/:/data/
      - ./caddy/config/:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
